
-- Create table
CREATE TABLE dbmover (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    foo VARCHAR(255)
) ENGINE='InnoDB' DEFAULT CHARSET='UTF8';

-- Alter table
CREATE TABLE dbmover (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    bar SMALLINT NOT NULL,
    foo VARCHAR(255)
) ENGINE='InnoDB' DEFAULT CHARSET='UTF8';

-- Create a view
CREATE VIEW test AS SELECT * FROM dbmover;

