
CREATE TABLE test (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bar SMALLINT NOT NULL,
    foo VARCHAR(255)
) ENGINE='InnoDB' DEFAULT CHARSET='UTF8';

ALTER TABLE test ADD COLUMN baz VARCHAR(16) NOT NULL DEFAULT 'fizz' AFTER bar;

CREATE PROCEDURE tmpinsert()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM test WHERE id = 1) THEN
        INSERT INTO test VALUES (1, 2, NULL, 'foo');
    END IF;
END;

CALL tmpinsert();

CREATE TRIGGER test_before_insert BEFORE INSERT ON test
FOR EACH ROW
BEGIN
    SET NEW.bar = NEW.bar + 1;
END;

