
CREATE TABLE dbmover (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    foo VARCHAR(255)
) ENGINE='InnoDB' DEFAULT CHARSET='UTF8';

CREATE TABLE dbmover_proc (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    sometext TEXT
) ENGINE='InnoDB' DEFAULT CHARSET='UTF8';

CREATE FUNCTION dbmover_test_function (str TEXT) RETURNS text
BEGIN
    RETURN LOWER(str);
END;

CREATE PROCEDURE dbmover_test_procedure (str TEXT)
BEGIN
    INSERT INTO dbmover_proc VALUES (NULL, str);
END;

